from sqlalchemy.orm import Session
from app.models import Recipe
from app.database import SessionLocal

# Mock data
mock_recipes = [
    {
        "name": "Spaghetti Carbonara",
        "image": "https://via.placeholder.com/300x200?text=Spaghetti+Carbonara",
        "time": 30,
        "category": "Italian",
        "isFavorite": False,
        "ingredients": [
            "200g spaghetti",
            "100g pancetta",
            "2 large eggs",
            "50g grated Parmesan cheese",
            "2 cloves garlic, minced",
            "Salt and black pepper to taste",
            "2 tbsp olive oil",
        ],
        "directions": [
            "Cook the spaghetti in a large pot of salted boiling water until al dente.",
            "In a pan, heat olive oil and sauté the pancetta until crispy.",
            "Add minced garlic to the pan and cook for 1 minute.",
            "In a bowl, whisk together eggs and Parmesan cheese.",
            "Drain the spaghetti and add it to the pan with pancetta and garlic.",
            "Remove the pan from heat and quickly mix in the egg and cheese mixture.",
            "Season with salt and black pepper, then serve immediately.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "450 kcal"},
            {"name": "Total fat", "measure": "18 g"},
            {"name": "Protein", "measure": "20 g"},
            {"name": "Carbohydrate", "measure": "50 g"},
            {"name": "Cholesterol", "measure": "150 mg"},
        ],
    },
    {
        "name": "Chicken Caesar Salad",
        "image": "https://via.placeholder.com/300x200?text=Chicken+Caesar+Salad",
        "time": 20,
        "category": "Salad",
        "isFavorite": False,
        "ingredients": [
            "2 chicken breasts",
            "1 head romaine lettuce",
            "50g croutons",
            "50g grated Parmesan cheese",
            "Caesar dressing",
            "Salt and black pepper to taste",
            "2 tbsp olive oil",
        ],
        "directions": [
            "Season the chicken breasts with salt and black pepper.",
            "Heat olive oil in a pan and cook the chicken until golden brown and cooked through.",
            "Chop the romaine lettuce and place it in a large bowl.",
            "Slice the cooked chicken and add it to the bowl with lettuce.",
            "Add croutons and Parmesan cheese to the bowl.",
            "Drizzle Caesar dressing over the salad and toss to combine.",
            "Serve immediately.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "320 kcal"},
            {"name": "Total fat", "measure": "12 g"},
            {"name": "Protein", "measure": "25 g"},
            {"name": "Carbohydrate", "measure": "20 g"},
            {"name": "Cholesterol", "measure": "80 mg"},
        ],
    },
    {
        "name": "Big and Juicy Wagyu Beef Cheeseburger",
        "image": "https://via.placeholder.com/300x200?text=Big+and+Juicy+Wagyu+Beef+Cheeseburger",
        "time": 40,
        "category": "American",
        "isFavorite": False,
        "ingredients": [
            "500g Wagyu beef patty",
            "4 burger buns",
            "4 slices cheddar cheese",
            "1 large tomato, sliced",
            "1 cup lettuce leaves",
            "1/2 cup mayonnaise",
            "1/4 cup ketchup",
            "1/4 cup mustard",
        ],
        "directions": [
            "Grill the Wagyu beef patties over medium heat until cooked to your liking.",
            "Toast the burger buns on the grill.",
            "Assemble the burgers by layering lettuce, tomato, beef patty, and cheddar cheese.",
            "Spread mayonnaise, ketchup, and mustard on the buns.",
            "Serve immediately with fries or chips.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "650 kcal"},
            {"name": "Total fat", "measure": "35 g"},
            {"name": "Protein", "measure": "40 g"},
            {"name": "Carbohydrate", "measure": "45 g"},
            {"name": "Cholesterol", "measure": "120 mg"},
        ],
    },
    {
        "name": "Fresh Lime Roasted Salmon with Ginger Sauce",
        "image": "https://via.placeholder.com/300x200?text=Fresh+Lime+Roasted+Salmon+with+Ginger+Sauce",
        "time": 25,
        "category": "Seafood",
        "isFavorite": False,
        "ingredients": [
            "4 salmon fillets",
            "2 limes, juiced",
            "2 tbsp soy sauce",
            "1 tbsp grated ginger",
            "2 cloves garlic, minced",
            "1 tbsp honey",
            "1 tbsp olive oil",
        ],
        "directions": [
            "Preheat the oven to 200°C (400°F).",
            "In a bowl, mix lime juice, soy sauce, ginger, garlic, honey, and olive oil.",
            "Place the salmon fillets on a baking tray and pour the sauce over them.",
            "Roast in the oven for 15-20 minutes until the salmon is cooked through.",
            "Serve with steamed vegetables or rice.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "300 kcal"},
            {"name": "Total fat", "measure": "15 g"},
            {"name": "Protein", "measure": "30 g"},
            {"name": "Carbohydrate", "measure": "5 g"},
            {"name": "Cholesterol", "measure": "70 mg"},
        ],
    },
    {
        "name": "Strawberry Oatmeal Pancake with Honey Syrup",
        "image": "https://via.placeholder.com/300x200?text=Strawberry+Oatmeal+Pancake+with+Honey+Syrup",
        "time": 20,
        "category": "Breakfast",
        "isFavorite": False,
        "ingredients": [
            "1 cup rolled oats",
            "1 cup all-purpose flour",
            "1/2 cup milk",
            "1 large egg",
            "1/4 cup honey",
            "1 cup fresh strawberries, sliced",
            "1 tsp baking powder",
            "1/4 tsp salt",
        ],
        "directions": [
            "In a bowl, mix oats, flour, baking powder, and salt.",
            "In another bowl, whisk milk, egg, and honey.",
            "Combine the wet and dry ingredients and mix until smooth.",
            "Heat a non-stick pan over medium heat and pour 1/4 cup of batter for each pancake.",
            "Cook until bubbles form, then flip and cook until golden brown.",
            "Top with fresh strawberries and drizzle with honey syrup.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "250 kcal"},
            {"name": "Total fat", "measure": "5 g"},
            {"name": "Protein", "measure": "6 g"},
            {"name": "Carbohydrate", "measure": "45 g"},
            {"name": "Cholesterol", "measure": "30 mg"},
        ],
    },
    {
        "name": "Chicken Meatballs with Cream Cheese",
        "image": "https://via.placeholder.com/300x200?text=Chicken+Meatballs+with+Cream+Cheese",
        "time": 35,
        "category": "Appetizer",
        "isFavorite": False,
        "ingredients": [
            "500g ground chicken",
            "1/2 cup breadcrumbs",
            "1/4 cup grated Parmesan cheese",
            "1 large egg",
            "2 tbsp chopped parsley",
            "1/2 tsp garlic powder",
            "1/2 tsp onion powder",
            "1/2 cup cream cheese",
        ],
        "directions": [
            "Preheat the oven to 200°C (400°F).",
            "In a bowl, mix ground chicken, breadcrumbs, Parmesan, egg, parsley, garlic powder, and onion powder.",
            "Form the mixture into small meatballs and place them on a baking tray.",
            "Bake for 20-25 minutes until golden brown and cooked through.",
            "Serve with cream cheese as a dipping sauce.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "300 kcal"},
            {"name": "Total fat", "measure": "15 g"},
            {"name": "Protein", "measure": "25 g"},
            {"name": "Carbohydrate", "measure": "10 g"},
            {"name": "Cholesterol", "measure": "80 mg"},
        ],
    },
    {
        "name": "Fresh and Healthy Mixed Mayonnaise Salad",
        "image": "https://via.placeholder.com/300x200?text=Fresh+and+Healthy+Mixed+Mayonnaise+Salad",
        "time": 15,
        "category": "Salad",
        "isFavorite": False,
        "ingredients": [
            "1 cup mixed greens",
            "1/2 cup cherry tomatoes, halved",
            "1/2 cup cucumber slices",
            "1/4 cup shredded carrots",
            "2 tbsp mayonnaise",
            "1 tbsp lemon juice",
            "Salt and black pepper to taste",
        ],
        "directions": [
            "In a large bowl, combine mixed greens, cherry tomatoes, cucumber, and carrots.",
            "In a small bowl, mix mayonnaise, lemon juice, salt, and black pepper.",
            "Pour the dressing over the salad and toss to combine.",
            "Serve immediately as a side dish or light meal.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "150 kcal"},
            {"name": "Total fat", "measure": "10 g"},
            {"name": "Protein", "measure": "2 g"},
            {"name": "Carbohydrate", "measure": "10 g"},
            {"name": "Cholesterol", "measure": "5 mg"},
        ],
    },
    {
        "name": "Fruity Pancake with Orange & Blueberry",
        "image": "https://via.placeholder.com/300x200?text=Fruity+Pancake+with+Orange+%26+Blueberry",
        "time": 25,
        "category": "Breakfast",
        "isFavorite": False,
        "ingredients": [
            "1 cup all-purpose flour",
            "1/2 cup milk",
            "1 large egg",
            "1/4 cup orange juice",
            "1/2 cup fresh blueberries",
            "1 tbsp sugar",
            "1 tsp baking powder",
            "1/4 tsp salt",
        ],
        "directions": [
            "In a bowl, mix flour, sugar, baking powder, and salt.",
            "In another bowl, whisk milk, egg, and orange juice.",
            "Combine the wet and dry ingredients and mix until smooth.",
            "Heat a non-stick pan over medium heat and pour 1/4 cup of batter for each pancake.",
            "Cook until bubbles form, then flip and cook until golden brown.",
            "Top with fresh blueberries and drizzle with orange syrup.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "220 kcal"},
            {"name": "Total fat", "measure": "4 g"},
            {"name": "Protein", "measure": "6 g"},
            {"name": "Carbohydrate", "measure": "40 g"},
            {"name": "Cholesterol", "measure": "30 mg"},
        ],
    },
    {
        "name": "The Best Easy One Pot Chicken and Rice",
        "image": "https://via.placeholder.com/300x200?text=The+Best+Easy+One+Pot+Chicken+and+Rice",
        "time": 40,
        "category": "Dinner",
        "isFavorite": False,
        "ingredients": [
            "2 chicken thighs",
            "1 cup long-grain rice",
            "2 cups chicken broth",
            "1 onion, diced",
            "2 cloves garlic, minced",
            "1/2 cup frozen peas",
            "1/2 tsp paprika",
            "Salt and black pepper to taste",
        ],
        "directions": [
            "Season the chicken thighs with salt, pepper, and paprika.",
            "In a large pot, sear the chicken thighs until golden brown, then set aside.",
            "In the same pot, sauté onion and garlic until fragrant.",
            "Add rice and chicken broth, then stir to combine.",
            "Place the chicken thighs back into the pot and cover.",
            "Cook on low heat for 20-25 minutes until the rice is tender.",
            "Add frozen peas and cook for another 5 minutes before serving.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "450 kcal"},
            {"name": "Total fat", "measure": "15 g"},
            {"name": "Protein", "measure": "30 g"},
            {"name": "Carbohydrate", "measure": "50 g"},
            {"name": "Cholesterol", "measure": "80 mg"},
        ],
    },
    {
        "name": "The Creamiest Creamy Chicken and Bacon Pasta",
        "image": "https://via.placeholder.com/300x200?text=The+Creamiest+Creamy+Chicken+and+Bacon+Pasta",
        "time": 30,
        "category": "Pasta",
        "isFavorite": False,
        "ingredients": [
            "200g pasta",
            "2 chicken breasts, diced",
            "4 slices bacon, chopped",
            "1 cup heavy cream",
            "1/2 cup grated Parmesan cheese",
            "2 cloves garlic, minced",
            "1 tbsp olive oil",
            "Salt and black pepper to taste",
        ],
        "directions": [
            "Cook the pasta in a large pot of salted boiling water until al dente, then drain.",
            "In a pan, heat olive oil and cook the bacon until crispy.",
            "Add diced chicken and cook until golden brown.",
            "Stir in minced garlic and cook for 1 minute.",
            "Pour in heavy cream and Parmesan cheese, then simmer until the sauce thickens.",
            "Add the cooked pasta to the pan and toss to coat.",
            "Season with salt and black pepper, then serve immediately.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "600 kcal"},
            {"name": "Total fat", "measure": "25 g"},
            {"name": "Protein", "measure": "35 g"},
            {"name": "Carbohydrate", "measure": "50 g"},
            {"name": "Cholesterol", "measure": "100 mg"},
        ],
    },
    {
        "name": "Spicy Delicious Chicken Wings",
        "image": "https://via.placeholder.com/300x200?text=Spicy+Delicious+Chicken+Wings",
        "time": 35,
        "category": "Appetizer",
        "isFavorite": False,
        "ingredients": [
            "1 kg chicken wings",
            "1/4 cup hot sauce",
            "2 tbsp butter, melted",
            "1 tbsp honey",
            "1 tsp garlic powder",
            "1 tsp paprika",
            "Salt and black pepper to taste",
        ],
        "directions": [
            "Preheat the oven to 200°C (400°F).",
            "In a bowl, mix hot sauce, melted butter, honey, garlic powder, paprika, salt, and black pepper.",
            "Toss the chicken wings in the sauce until evenly coated.",
            "Place the wings on a baking tray lined with parchment paper.",
            "Bake for 25-30 minutes, flipping halfway through, until crispy and cooked through.",
            "Serve with ranch dressing or blue cheese dip.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "400 kcal"},
            {"name": "Total fat", "measure": "25 g"},
            {"name": "Protein", "measure": "30 g"},
            {"name": "Carbohydrate", "measure": "10 g"},
            {"name": "Cholesterol", "measure": "90 mg"},
        ],
    },
    {
        "name": "Mixed Tropical Fruit Salad with Superfood Boosts",
        "image": "https://via.placeholder.com/300x200?text=Mixed+Tropical+Fruit+Salad+with+Superfood+Boosts",
        "time": 15,
        "category": "Dessert",
        "isFavorite": False,
        "ingredients": [
            "1 cup diced pineapple",
            "1 cup diced mango",
            "1 cup sliced kiwi",
            "1/2 cup blueberries",
            "1/4 cup pomegranate seeds",
            "1 tbsp chia seeds",
            "1 tbsp honey",
            "1 tbsp lime juice",
        ],
        "directions": [
            "In a large bowl, combine pineapple, mango, kiwi, blueberries, and pomegranate seeds.",
            "In a small bowl, mix honey, lime juice, and chia seeds.",
            "Pour the dressing over the fruit and toss gently to combine.",
            "Serve immediately or chill in the refrigerator before serving.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "180 kcal"},
            {"name": "Total fat", "measure": "2 g"},
            {"name": "Protein", "measure": "3 g"},
            {"name": "Carbohydrate", "measure": "40 g"},
            {"name": "Cholesterol", "measure": "0 mg"},
        ],
    },
    {
        "name": "Big and Juicy Wagyu Beef Cheeseburger",
        "image": "https://via.placeholder.com/300x200?text=Big+and+Juicy+Wagyu+Beef+Cheeseburger",
        "time": 40,
        "category": "American",
        "isFavorite": False,
        "ingredients": [
            "500g Wagyu beef patty",
            "4 burger buns",
            "4 slices cheddar cheese",
            "1 large tomato, sliced",
            "1 cup lettuce leaves",
            "1/2 cup mayonnaise",
            "1/4 cup ketchup",
            "1/4 cup mustard",
        ],
        "directions": [
            "Grill the Wagyu beef patties over medium heat until cooked to your liking.",
            "Toast the burger buns on the grill.",
            "Assemble the burgers by layering lettuce, tomato, beef patty, and cheddar cheese.",
            "Spread mayonnaise, ketchup, and mustard on the buns.",
            "Serve immediately with fries or chips.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "650 kcal"},
            {"name": "Total fat", "measure": "35 g"},
            {"name": "Protein", "measure": "40 g"},
            {"name": "Carbohydrate", "measure": "45 g"},
            {"name": "Cholesterol", "measure": "120 mg"},
        ],
    },
    {
        "name": "Healthy Japanese Fried Rice with Asparagus",
        "image": "https://via.placeholder.com/300x200?text=Healthy+Japanese+Fried+Rice+with+Asparagus",
        "time": 30,
        "category": "Asian",
        "isFavorite": False,
        "ingredients": [
            "2 cups cooked rice",
            "1 cup asparagus, chopped",
            "1/2 cup diced carrots",
            "1/2 cup peas",
            "2 eggs, beaten",
            "2 tbsp soy sauce",
            "1 tbsp sesame oil",
            "2 cloves garlic, minced",
        ],
        "directions": [
            "Heat sesame oil in a large pan or wok over medium heat.",
            "Add garlic and sauté until fragrant.",
            "Add carrots, peas, and asparagus, and stir-fry for 5 minutes.",
            "Push the vegetables to one side and scramble the eggs on the other side.",
            "Add the cooked rice and soy sauce, and stir everything together.",
            "Cook for another 2-3 minutes, then serve hot.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "300 kcal"},
            {"name": "Total fat", "measure": "8 g"},
            {"name": "Protein", "measure": "10 g"},
            {"name": "Carbohydrate", "measure": "45 g"},
            {"name": "Cholesterol", "measure": "70 mg"},
        ],
    },
    {
        "name": "Cauliflower Walnut Vegetarian Taco Meat",
        "image": "https://via.placeholder.com/300x200?text=Cauliflower+Walnut+Vegetarian+Taco+Meat",
        "time": 25,
        "category": "Mexican",
        "isFavorite": False,
        "ingredients": [
            "1 head cauliflower, finely chopped",
            "1 cup walnuts, finely chopped",
            "2 tbsp olive oil",
            "1 tbsp chili powder",
            "1 tsp cumin",
            "1 tsp smoked paprika",
            "Salt and black pepper to taste",
            "8 taco shells",
        ],
        "directions": [
            "Preheat the oven to 200°C (400°F).",
            "In a bowl, mix cauliflower, walnuts, olive oil, chili powder, cumin, paprika, salt, and pepper.",
            "Spread the mixture on a baking sheet and roast for 20 minutes, stirring halfway through.",
            "Warm the taco shells and fill them with the roasted cauliflower-walnut mixture.",
            "Top with your favorite taco toppings and serve.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "250 kcal"},
            {"name": "Total fat", "measure": "12 g"},
            {"name": "Protein", "measure": "8 g"},
            {"name": "Carbohydrate", "measure": "30 g"},
            {"name": "Cholesterol", "measure": "0 mg"},
        ],
    },
    {
        "name": "Chicken Ramen Soup with Mushroom",
        "image": "https://via.placeholder.com/300x200?text=Chicken+Ramen+Soup+with+Mushroom",
        "time": 40,
        "category": "Asian",
        "isFavorite": False,
        "ingredients": [
            "2 chicken thighs",
            "4 cups chicken broth",
            "200g ramen noodles",
            "1 cup sliced mushrooms",
            "2 cloves garlic, minced",
            "1 tbsp soy sauce",
            "1 tsp sesame oil",
            "1 boiled egg, halved",
        ],
        "directions": [
            "In a pot, heat sesame oil and sauté garlic until fragrant.",
            "Add chicken thighs and cook until browned on both sides.",
            "Pour in chicken broth and bring to a boil. Simmer for 20 minutes.",
            "Remove the chicken, shred it, and return it to the pot.",
            "Add mushrooms, soy sauce, and ramen noodles, and cook for 5 minutes.",
            "Serve hot, topped with a boiled egg and green onions.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "400 kcal"},
            {"name": "Total fat", "measure": "15 g"},
            {"name": "Protein", "measure": "25 g"},
            {"name": "Carbohydrate", "measure": "40 g"},
            {"name": "Cholesterol", "measure": "90 mg"},
        ],
    },
    {
        "name": "Firecracker Vegan Lettuce Wraps - Spicy!",
        "image": "https://via.placeholder.com/300x200?text=Firecracker+Vegan+Lettuce+Wraps",
        "time": 20,
        "category": "Vegan",
        "isFavorite": False,
        "ingredients": [
            "1 cup cooked quinoa",
            "1 cup diced tofu",
            "1/2 cup diced bell peppers",
            "1/4 cup firecracker sauce",
            "1 tbsp olive oil",
            "1 head lettuce, leaves separated",
            "Salt and black pepper to taste",
        ],
        "directions": [
            "Heat olive oil in a pan and sauté tofu until golden brown.",
            "Add bell peppers and cook for 2-3 minutes.",
            "Stir in cooked quinoa and firecracker sauce, and cook for another 2 minutes.",
            "Spoon the mixture into lettuce leaves and serve immediately.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "200 kcal"},
            {"name": "Total fat", "measure": "8 g"},
            {"name": "Protein", "measure": "10 g"},
            {"name": "Carbohydrate", "measure": "25 g"},
            {"name": "Cholesterol", "measure": "0 mg"},
        ],
    },
    {
        "name": "Barbeque Spicy Sandwiches with Chips",
        "image": "https://via.placeholder.com/300x200?text=Barbeque+Spicy+Sandwiches+with+Chips",
        "time": 25,
        "category": "American",
        "isFavorite": False,
        "ingredients": [
            "4 sandwich buns",
            "2 cups shredded chicken",
            "1/2 cup barbecue sauce",
            "1/4 cup sliced jalapeños",
            "1/2 cup coleslaw",
            "1 bag potato chips",
        ],
        "directions": [
            "In a bowl, mix shredded chicken with barbecue sauce.",
            "Toast the sandwich buns and layer with chicken, jalapeños, and coleslaw.",
            "Serve with a side of potato chips.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "450 kcal"},
            {"name": "Total fat", "measure": "15 g"},
            {"name": "Protein", "measure": "25 g"},
            {"name": "Carbohydrate", "measure": "50 g"},
            {"name": "Cholesterol", "measure": "60 mg"},
        ],
    },
    {
        "name": "Rainbow Chicken Salad with Almond Honey Mustard Dressing",
        "image": "https://via.placeholder.com/300x200?text=Rainbow+Chicken+Salad",
        "time": 30,
        "category": "Salad",
        "isFavorite": False,
        "ingredients": [
            "2 chicken breasts, grilled and sliced",
            "1 cup mixed greens",
            "1/2 cup shredded carrots",
            "1/2 cup diced bell peppers",
            "1/4 cup sliced almonds",
            "2 tbsp honey mustard dressing",
        ],
        "directions": [
            "In a large bowl, combine mixed greens, carrots, bell peppers, and almonds.",
            "Top with grilled chicken slices.",
            "Drizzle honey mustard dressing over the salad and toss to combine.",
            "Serve immediately.",
        ],
        "nutritionInfo": [
            {"name": "Calories", "measure": "350 kcal"},
            {"name": "Total fat", "measure": "12 g"},
            {"name": "Protein", "measure": "30 g"},
            {"name": "Carbohydrate", "measure": "20 g"},
            {"name": "Cholesterol", "measure": "70 mg"},
        ],
    },
]

# Function to populate the database
def populate_db():
    db: Session = SessionLocal()
    try:    
        for recipe_data in mock_recipes:
            recipe = Recipe(**recipe_data)
            db.add(recipe)
        db.commit()
        print("Database populated successfully!")
    except Exception as e:
        db.rollback()
        print(f"Error populating database: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    populate_db()